### ISSUE TITLE
Error issue line 152 php 8.1+

### ISSUE THREAD

**Issue by alexonbstudio** [WPManageNinja/fluent-auth#25]
WordPress version 6.2.2
Thème actif : Hello Elementor (version 2.8.1)
Extension actuelle : FluentAuth - Auth Security Plugin (version 1.0.5)
PHP version 8.1.18

Détails de l’erreur
======================
Une erreur de type E_ERROR a été causée dans la ligne 152 du fichier /[wordpress-sites-hosting]/wp-content/plugins/fluent-security/app/Hooks/Handlers/LoginSecurityHandler.php. Message d’erreur : Uncaught ArgumentCountError: Too few arguments to function FluentAuth\App\Hooks\Handlers\LoginSecurityHandler::logAuthSuccess(), 1 passed in /[wordpress-sites-hosting]/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /[wordpress-sites-hosting]/wp-content/plugins/fluent-security/app/Hooks/Handlers/LoginSecurityHandler.php:152
Stack trace:
#0 /[wordpress-sites-hosting]/wp-includes/class-wp-hook.php(308): FluentAuth\App\Hooks\Handlers\LoginSecurityHandler->logAuthSuccess()
#1 /[wordpress-sites-hosting]/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /[wordpress-sites-hosting]/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /[wordpress-sites-hosting]/wp-includes/class-wp-hook.php(308): nop_auto_login()
#5 /[wordpress-sites-hosting]/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#6 /[wordpress-sites-hosting]/wp-includes/pluggable.php(616): apply_filters()
#7 /[wordpress-sites-hosting]/wp-includes/user.php(106): wp_authenticate()
#8 /[wordpress-sites-hosting]/wp-login.php(1241): wp_signon()
#9 {main}
  thrown

**Comment by techjewel** [comment]
the issue has been resolved
